-- audit_setup.sql
SET SERVEROUTPUT ON;
SET FEEDBACK ON;

PROMPT Creating audit_log table...
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE audit_log CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('Dropped existing audit_log table');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('No existing audit_log table to drop');
END;

-- Create audit_log table
CREATE TABLE audit_log (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(50) NOT NULL,
    operation_type VARCHAR2(10) NOT NULL,
    operation_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    user_name VARCHAR2(50) DEFAULT USER NOT NULL,
    offender_id NUMBER,
    program_id NUMBER,
    old_values VARCHAR2(4000),
    new_values VARCHAR2(4000),
    restriction_violated VARCHAR2(1) DEFAULT 'N',
    error_message VARCHAR2(500)
);

-- Create indexes
PROMPT Creating indexes...
CREATE INDEX idx_audit_date ON audit_log(operation_date);
CREATE INDEX idx_audit_user ON audit_log(user_name);
CREATE INDEX idx_audit_offender ON audit_log(offender_id);
CREATE INDEX idx_audit_restriction ON audit_log(restriction_violated);

-- Create audit logging function
PROMPT Creating log_audit_trail function...
CREATE OR REPLACE FUNCTION log_audit_trail(
    p_table_name IN VARCHAR2,
    p_operation_type IN VARCHAR2,
    p_offender_id IN NUMBER DEFAULT NULL,
    p_program_id IN NUMBER DEFAULT NULL,
    p_old_values IN VARCHAR2 DEFAULT NULL,
    p_new_values IN VARCHAR2 DEFAULT NULL,
    p_restriction_violated IN VARCHAR2 DEFAULT 'N',
    p_error_message IN VARCHAR2 DEFAULT NULL
) RETURN NUMBER
IS
    PRAGMA AUTONOMOUS_TRANSACTION;
    v_audit_id NUMBER;
BEGIN
    INSERT INTO audit_log (
        table_name,
        operation_type,
        offender_id,
        program_id,
        old_values,
        new_values,
        restriction_violated,
        error_message
    ) VALUES (
        p_table_name,
        p_operation_type,
        p_offender_id,
        p_program_id,
        p_old_values,
        p_new_values,
        p_restriction_violated,
        p_error_message
    )
    RETURNING audit_id INTO v_audit_id;
    
    COMMIT;
    RETURN v_audit_id;
    
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Audit logging error: ' || SQLERRM);
        RETURN -1;
END;
/

-- Create restriction check function
PROMPT Creating check_restriction_allowed function...
CREATE OR REPLACE FUNCTION check_restriction_allowed
RETURN BOOLEAN
IS
    v_current_day VARCHAR2(20);
    v_is_holiday NUMBER;
BEGIN
    -- Get current day of week
    SELECT TO_CHAR(SYSDATE, 'DY') INTO v_current_day FROM dual;
    
    -- Check if today is a weekday (Monday-Friday)
    IF v_current_day IN ('MON', 'TUE', 'WED', 'THU', 'FRI') THEN
        RETURN FALSE;
    END IF;
    
    -- Check if today is a holiday (if holiday_management table exists)
    BEGIN
        SELECT COUNT(*) INTO v_is_holiday
        FROM holiday_management
        WHERE TRUNC(holiday_date) = TRUNC(SYSDATE);
        
        IF v_is_holiday > 0 THEN
            RETURN FALSE;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            -- If holiday_management table doesn't exist, ignore holiday check
            NULL;
    END;
    
    -- If we get here, operation is allowed (weekend and not a holiday)
    RETURN TRUE;
    
EXCEPTION
    WHEN OTHERS THEN
        -- In case of error, default to allowing the operation (fail-safe)
        RETURN TRUE;
END;
/

-- Test the functions
PROMPT Testing functions...
DECLARE
    v_test_id NUMBER;
    v_test_result VARCHAR2(200);
BEGIN
    -- Test the audit function
    v_test_id := log_audit_trail(
        p_table_name => 'SYSTEM',
        p_operation_type => 'SETUP',
        p_old_values => 'Audit system setup',
        p_new_values => 'Audit system created successfully'
    );
    
    DBMS_OUTPUT.PUT_LINE('✓ Audit function test: Created audit ID ' || v_test_id);
    
    -- Test the restriction function
    IF check_restriction_allowed THEN
        v_test_result := 'Operations are ALLOWED (weekend/not holiday)';
    ELSE
        v_test_result := 'Operations are NOT ALLOWED (weekday/holiday)';
    END IF;
    
    DBMS_OUTPUT.PUT_LINE('✓ Restriction function test: ' || v_test_result);
    
END;
/

